AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: lambda-parallel-router Mode A Runtime API proxy layer

Resources:
  LprRuntimeApiProxyLayerArm64:
    Type: AWS::Serverless::LayerVersion
    Metadata:
      BuildMethod: makefile
      BuildArchitecture: arm64
    Properties:
      RetentionPolicy: Retain
      LayerName: !Sub "${AWS::StackName}-lpr-runtime-api-proxy-arm64"
      ContentUri: .
      CompatibleArchitectures:
        - arm64

  LprRuntimeApiProxyLayerAmd64:
    Type: AWS::Serverless::LayerVersion
    Metadata:
      BuildMethod: makefile
      BuildArchitecture: x86_64
    Properties:
      RetentionPolicy: Retain
      LayerName: !Sub "${AWS::StackName}-lpr-runtime-api-proxy-amd64"
      ContentUri: .
      CompatibleArchitectures:
        - x86_64

Outputs:
  LayerArm64Arn:
    Description: ARN of the arm64 layer
    Value: !Ref LprRuntimeApiProxyLayerArm64
  LayerAmd64Arn:
    Description: ARN of the amd64 layer
    Value: !Ref LprRuntimeApiProxyLayerAmd64
