AWSTemplateFormatVersion: "2010-09-09"
Transform:
  - AWS::Serverless-2016-10-31
  - LprRouter
Description: lambda-parallel-router demo (App Runner + sample Lambda batch handlers)

Parameters:
  RouterImageIdentifier:
    Type: String
    Description: ECR image identifier for the router container (e.g. 123456789012.dkr.ecr.us-east-1.amazonaws.com/lambda-parallel-router/router:latest).

Globals:
  Function:
    Runtime: nodejs24.x
    Handler: app.handler
    Timeout: 10
    MemorySize: 256
    LoggingConfig:
      ApplicationLogLevel: INFO
      LogFormat: JSON

Resources:

  # ------------------------------
  # Sample Lambda functions
  # ------------------------------
  SampleBufferingSimpleHelloFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/buffering-simple/
      FunctionName: !Sub '${AWS::StackName}-buffering-simple-hello'
      Description: Demo batch handler (buffered, simple).
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        EntryPoints:
          - app.ts
        Format: cjs
        Minify: false
        Sourcemap: false
        Target: es2020

  SampleBufferingDynamicHelloFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/buffering-dynamic/
      FunctionName: !Sub '${AWS::StackName}-buffering-dynamic-hello'
      Description: Demo batch handler (buffered, dynamic).
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        EntryPoints:
          - app.ts
        Format: cjs
        Minify: false
        Sourcemap: false
        Target: es2020

  SampleStreamingSimpleHelloFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/streaming-simple/
      FunctionName: !Sub '${AWS::StackName}-streaming-simple-hello'
      Description: Demo batch handler (streaming, simple).
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        EntryPoints:
          - app.ts
        Format: cjs
        Minify: false
        Sourcemap: false
        Target: es2020

  SampleStreamingDynamicHelloFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/streaming-dynamic/
      FunctionName: !Sub '${AWS::StackName}-streaming-dynamic-hello'
      Description: Demo batch handler (streaming, dynamic).
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        EntryPoints:
          - app.ts
        Format: cjs
        Minify: false
        Sourcemap: false
        Target: es2020

  SampleBufferingAdapterHelloFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/buffering-adapter/
      FunctionName: !Sub '${AWS::StackName}-buffering-adapter-hello'
      Description: Demo batch handler (buffered, adapter).
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        EntryPoints:
          - app.ts
        Format: cjs
        Minify: false
        Sourcemap: false
        Target: es2020

  SampleStreamingAdapterHelloFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/streaming-adapter/
      FunctionName: !Sub '${AWS::StackName}-streaming-adapter-hello'
      Description: Demo batch handler (streaming, adapter).
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        EntryPoints:
          - app.ts
        Format: cjs
        Minify: false
        Sourcemap: false
        Target: es2020

  SampleStreamingAdapterSseFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/streaming-adapter-sse/
      FunctionName: !Sub '${AWS::StackName}-streaming-adapter-sse'
      Description: Demo batch handler (streaming, adapter, SSE).
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        EntryPoints:
          - app.ts
        Format: cjs
        Minify: false
        Sourcemap: false
        Target: es2020

  # ------------------------------
  # Router service (expanded by the LprRouter macro)
  # ------------------------------
  RouterService:
    Type: Lpr::Router::Service
    Properties:
      ServiceName: !Sub '${AWS::StackName}-service'
      ImageIdentifier: !Ref RouterImageIdentifier
      Port: 8080
      Environment:
        RUST_LOG: info
      RouterConfig: {}
      Spec:
        openapi: 3.0.0
        info:
          title: lambda-parallel-router demo
          version: "1"
        paths:
          /buffering/simple/hello:
            get:
              x-target-lambda: !GetAtt SampleBufferingSimpleHelloFunction.Arn
              x-lpr:
                max_wait_ms: 25
                max_batch_size: 4
                invoke_mode: buffered
                timeout_ms: 8000
          /buffering/dynamic/hello:
            get:
              x-target-lambda: !GetAtt SampleBufferingDynamicHelloFunction.Arn
              x-lpr:
                max_wait_ms: 100
                max_batch_size: 16
                invoke_mode: buffered
                timeout_ms: 8000
                dynamic_wait:
                  min_wait_ms: 1
                  target_rps: 50
                  steepness: 0.05
                  sampling_interval_ms: 100
                  smoothing_samples: 5
          /streaming/simple/hello:
            get:
              x-target-lambda: !GetAtt SampleStreamingSimpleHelloFunction.Arn
              x-lpr:
                max_wait_ms: 25
                max_batch_size: 4
                invoke_mode: response_stream
                timeout_ms: 8000
          /streaming/dynamic/hello:
            get:
              x-target-lambda: !GetAtt SampleStreamingDynamicHelloFunction.Arn
              x-lpr:
                max_wait_ms: 100
                max_batch_size: 16
                invoke_mode: response_stream
                timeout_ms: 8000
                dynamic_wait:
                  min_wait_ms: 1
                  target_rps: 50
                  steepness: 0.05
                  sampling_interval_ms: 100
                  smoothing_samples: 5
          /buffering/adapter/hello:
            get:
              x-target-lambda: !GetAtt SampleBufferingAdapterHelloFunction.Arn
              x-lpr:
                max_wait_ms: 25
                max_batch_size: 4
                invoke_mode: buffered
                timeout_ms: 8000
          /streaming/adapter/hello:
            get:
              x-target-lambda: !GetAtt SampleStreamingAdapterHelloFunction.Arn
              x-lpr:
                max_wait_ms: 25
                max_batch_size: 4
                invoke_mode: response_stream
                timeout_ms: 8000
          /streaming/adapter/sse:
            get:
              x-target-lambda: !GetAtt SampleStreamingAdapterSseFunction.Arn
              x-lpr:
                max_wait_ms: 25
                max_batch_size: 4
                invoke_mode: response_stream
                timeout_ms: 8000

Outputs:
  SampleBufferingSimpleHelloFunctionArn:
    Value: !GetAtt SampleBufferingSimpleHelloFunction.Arn

  SampleBufferingDynamicHelloFunctionArn:
    Value: !GetAtt SampleBufferingDynamicHelloFunction.Arn

  SampleStreamingSimpleHelloFunctionArn:
    Value: !GetAtt SampleStreamingSimpleHelloFunction.Arn

  SampleStreamingDynamicHelloFunctionArn:
    Value: !GetAtt SampleStreamingDynamicHelloFunction.Arn

  SampleBufferingAdapterHelloFunctionArn:
    Value: !GetAtt SampleBufferingAdapterHelloFunction.Arn

  SampleStreamingAdapterHelloFunctionArn:
    Value: !GetAtt SampleStreamingAdapterHelloFunction.Arn

  SampleStreamingAdapterSseFunctionArn:
    Value: !GetAtt SampleStreamingAdapterSseFunction.Arn

  RouterImageIdentifier:
    Value: !Ref RouterImageIdentifier

  RouterServiceUrl:
    Value: !GetAtt RouterService.ServiceUrl
