AWSTemplateFormatVersion: "2010-09-09"
Transform:
  - AWS::Serverless-2016-10-31
  - LprRouter
Description: lambda-parallel-router demo (App Runner + sample Lambda batch handlers)

Parameters:
  OtelTracesEndpoint:
    Type: String
    Default: https://api.honeycomb.io/v1/traces
    Description: OTLP traces endpoint URL (used as-is, not modified by the router).
  OtelTracesProtocol:
    Type: String
    Default: http/protobuf
    AllowedValues:
      - http/protobuf
      - grpc
    Description: OTLP protocol to use for exporting traces.
  OtelHeadersSecretArn:
    Type: String
    Description: Secrets Manager secret ARN containing a JSON object of HTTP headers to send with OTLP requests.

Globals:
  Function:
    Runtime: nodejs24.x
    Handler: app.handler
    Timeout: 10
    MemorySize: 256
    Tracing: Active
    LoggingConfig:
      ApplicationLogLevel: INFO
      LogFormat: JSON

Resources:

  # ------------------------------
  # Sample Lambda functions
  # ------------------------------
  BenchmarkItemsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${AWS::StackName}-benchmark-items"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
      TimeToLiveSpecification:
        AttributeName: expiresAt
        Enabled: true

  LprRuntimeApiProxyLayerAmd64:
    Type: AWS::Serverless::LayerVersion
    Metadata:
      BuildMethod: makefile
      BuildArchitecture: x86_64
    Properties:
      RetentionPolicy: Retain
      LayerName: !Sub "${AWS::StackName}-lpr-runtime-api-proxy-amd64"
      ContentUri: ../bootstrap/layer-proxy
      CompatibleArchitectures:
        - x86_64

  SampleBufferingSimpleHelloFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/buffering-simple/
      FunctionName: !Sub '${AWS::StackName}-buffering-simple-hello'
      Description: Demo batch handler (buffered, simple).
      Environment:
        Variables:
          BENCHMARK_TABLE_NAME: !Ref BenchmarkItemsTable
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref BenchmarkItemsTable
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        EntryPoints:
          - app.ts
        External:
          - "@aws-sdk/*"
        Format: cjs
        Minify: false
        Sourcemap: false
        Target: es2020

  SampleBufferingDynamicHelloFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/buffering-dynamic/
      FunctionName: !Sub '${AWS::StackName}-buffering-dynamic-hello'
      Description: Demo batch handler (buffered, dynamic).
      Environment:
        Variables:
          BENCHMARK_TABLE_NAME: !Ref BenchmarkItemsTable
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref BenchmarkItemsTable
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        EntryPoints:
          - app.ts
        External:
          - "@aws-sdk/*"
        Format: cjs
        Minify: false
        Sourcemap: false
        Target: es2020

  SampleStreamingSimpleHelloFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/streaming-simple/
      FunctionName: !Sub '${AWS::StackName}-streaming-simple-hello'
      Description: Demo batch handler (streaming, simple).
      Environment:
        Variables:
          BENCHMARK_TABLE_NAME: !Ref BenchmarkItemsTable
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref BenchmarkItemsTable
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        EntryPoints:
          - app.ts
        External:
          - "@aws-sdk/*"
        Format: cjs
        Minify: false
        Sourcemap: false
        Target: es2020

  SampleStreamingDynamicHelloFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/streaming-dynamic/
      FunctionName: !Sub '${AWS::StackName}-streaming-dynamic-hello'
      Description: Demo batch handler (streaming, dynamic).
      Environment:
        Variables:
          BENCHMARK_TABLE_NAME: !Ref BenchmarkItemsTable
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref BenchmarkItemsTable
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        EntryPoints:
          - app.ts
        External:
          - "@aws-sdk/*"
        Format: cjs
        Minify: false
        Sourcemap: false
        Target: es2020

  SampleBufferingAdapterHelloFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/buffering-adapter/
      FunctionName: !Sub '${AWS::StackName}-buffering-adapter-hello'
      Description: Demo batch handler (buffered, adapter).
      Environment:
        Variables:
          BENCHMARK_TABLE_NAME: !Ref BenchmarkItemsTable
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref BenchmarkItemsTable
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        EntryPoints:
          - app.ts
        External:
          - "@aws-sdk/*"
        Format: cjs
        Minify: false
        Sourcemap: false
        Target: es2020

  SampleStreamingAdapterHelloFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/streaming-adapter/
      FunctionName: !Sub '${AWS::StackName}-streaming-adapter-hello'
      Description: Demo batch handler (streaming, adapter).
      Environment:
        Variables:
          BENCHMARK_TABLE_NAME: !Ref BenchmarkItemsTable
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref BenchmarkItemsTable
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        EntryPoints:
          - app.ts
        External:
          - "@aws-sdk/*"
        Format: cjs
        Minify: false
        Sourcemap: false
        Target: es2020

  SampleStreamingAdapterSseFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/streaming-adapter-sse/
      FunctionName: !Sub '${AWS::StackName}-streaming-adapter-sse'
      Description: Demo batch handler (streaming, adapter, SSE).
      Environment:
        Variables:
          BENCHMARK_TABLE_NAME: !Ref BenchmarkItemsTable
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref BenchmarkItemsTable
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        EntryPoints:
          - app.ts
        External:
          - "@aws-sdk/*"
        Format: cjs
        Minify: false
        Sourcemap: false
        Target: es2020

  DirectHelloFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/direct-hello/
      FunctionName: !Sub '${AWS::StackName}-direct-hello'
      Description: Demo handler exposed via a Lambda Function URL (direct invoke).
      Environment:
        Variables:
          BENCHMARK_TABLE_NAME: !Ref BenchmarkItemsTable
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref BenchmarkItemsTable
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        EntryPoints:
          - app.ts
        External:
          - "@aws-sdk/*"
        Format: cjs
        Minify: false
        Sourcemap: false
        Target: es2020

  DirectHelloFunctionUrl:
    Type: AWS::Lambda::Url
    Properties:
      AuthType: NONE
      TargetFunctionArn: !GetAtt DirectHelloFunction.Arn

  DirectHelloFunctionUrlPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunctionUrl
      FunctionName: !Ref DirectHelloFunction
      Principal: "*"
      FunctionUrlAuthType: NONE

  SampleStreamingModeALayerProxyPythonHelloFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.14
      CodeUri: lambda/streaming-mode-a-layer-proxy-python/
      FunctionName: !Sub '${AWS::StackName}-layer-proxy-python-hello'
      Description: Demo handler (streaming, Mode A, layer proxy, Python).
      Architectures:
        - x86_64
      Layers:
        - !Ref LprRuntimeApiProxyLayerAmd64
      Environment:
        Variables:
          AWS_LAMBDA_EXEC_WRAPPER: /opt/lpr/exec-wrapper.sh
          LPR_MAX_CONCURRENCY: "4"
          BENCHMARK_TABLE_NAME: !Ref BenchmarkItemsTable
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref BenchmarkItemsTable

  SampleStreamingModeALayerProxyNodeHelloFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/streaming-mode-a-layer-proxy-node/
      FunctionName: !Sub '${AWS::StackName}-layer-proxy-node-hello'
      Description: Demo handler (streaming, Mode A, layer proxy, Node).
      Architectures:
        - x86_64
      Layers:
        - !Ref LprRuntimeApiProxyLayerAmd64
      Environment:
        Variables:
          AWS_LAMBDA_EXEC_WRAPPER: /opt/lpr/exec-wrapper.sh
          BENCHMARK_TABLE_NAME: !Ref BenchmarkItemsTable
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref BenchmarkItemsTable
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        EntryPoints:
          - app.ts
        External:
          - "@aws-sdk/*"
        Format: cjs
        Minify: false
        Sourcemap: false
        Target: es2020

  # ------------------------------
  # Router service (expanded by the LprRouter macro)
  # ------------------------------
  RouterService:
    Type: Lpr::Router::Service
    Properties:
      ServiceName: !Sub '${AWS::StackName}-service'
      Port: 8080
      Environment:
        RUST_LOG: info
        LPR_INCLUDE_BATCH_SIZE_HEADER: "1"
      InstanceConfiguration:
        Cpu: "1 vCPU"
        Memory: "2 GB"
      AutoScalingConfiguration:
        MaxConcurrency: 100
        MinSize: 4
        MaxSize: 8
      RouterConfig:
        DefaultTimeoutMs: 2000
      ObservabilityConfiguration:
        Vendor: OTEL
        OpentelemetryConfiguration:
          TracesEndpoint: !Ref OtelTracesEndpoint
          Protocol: !Ref OtelTracesProtocol
          HeadersSecretArn: !Ref OtelHeadersSecretArn
      Spec:
        openapi: 3.0.0
        info:
          title: lambda-parallel-router demo
          version: "1"
        paths:
          /buffering/simple/{greeting}:
            get:
              x-target-lambda: !GetAtt SampleBufferingSimpleHelloFunction.Arn
              x-lpr:
                maxWaitMs: 25
                maxBatchSize: 4
                invokeMode: buffered
                timeoutMs: 8000
          /buffering/simple/item/{id}:
            get:
              x-target-lambda: !GetAtt SampleBufferingSimpleHelloFunction.Arn
              x-lpr:
                maxWaitMs: 25
                maxBatchSize: 4
                invokeMode: buffered
                timeoutMs: 8000
          /buffering/dynamic/{greeting}:
            get:
              x-target-lambda: !GetAtt SampleBufferingDynamicHelloFunction.Arn
              x-lpr:
                maxWaitMs: 100
                maxBatchSize: 16
                invokeMode: buffered
                timeoutMs: 8000
                dynamicWait:
                  minWaitMs: 1
                  targetRps: 50
                  steepness: 0.05
                  samplingIntervalMs: 100
                  smoothingSamples: 5
          /buffering/dynamic/item/{id}:
            get:
              x-target-lambda: !GetAtt SampleBufferingDynamicHelloFunction.Arn
              x-lpr:
                maxWaitMs: 100
                maxBatchSize: 16
                invokeMode: buffered
                timeoutMs: 8000
                dynamicWait:
                  minWaitMs: 1
                  targetRps: 50
                  steepness: 0.05
                  samplingIntervalMs: 100
                  smoothingSamples: 5
          /streaming/simple/{greeting}:
            get:
              x-target-lambda: !GetAtt SampleStreamingSimpleHelloFunction.Arn
              x-lpr:
                maxWaitMs: 25
                maxBatchSize: 4
                invokeMode: response_stream
                timeoutMs: 8000
          /streaming/simple/item/{id}:
            get:
              x-target-lambda: !GetAtt SampleStreamingSimpleHelloFunction.Arn
              x-lpr:
                maxWaitMs: 25
                maxBatchSize: 4
                invokeMode: response_stream
                timeoutMs: 8000
          /streaming/dynamic/{greeting}:
            get:
              x-target-lambda: !GetAtt SampleStreamingDynamicHelloFunction.Arn
              x-lpr:
                maxWaitMs: 100
                maxBatchSize: 16
                invokeMode: response_stream
                timeoutMs: 8000
                dynamicWait:
                  minWaitMs: 1
                  targetRps: 50
                  steepness: 0.05
                  samplingIntervalMs: 100
                  smoothingSamples: 5
          /streaming/dynamic/item/{id}:
            get:
              x-target-lambda: !GetAtt SampleStreamingDynamicHelloFunction.Arn
              x-lpr:
                maxWaitMs: 100
                maxBatchSize: 16
                invokeMode: response_stream
                timeoutMs: 8000
                dynamicWait:
                  minWaitMs: 1
                  targetRps: 50
                  steepness: 0.05
                  samplingIntervalMs: 100
                  smoothingSamples: 5
          /buffering/adapter/{greeting}:
            get:
              x-target-lambda: !GetAtt SampleBufferingAdapterHelloFunction.Arn
              x-lpr:
                maxWaitMs: 25
                maxBatchSize: 4
                invokeMode: buffered
                timeoutMs: 8000
          /buffering/adapter/item/{id}:
            get:
              x-target-lambda: !GetAtt SampleBufferingAdapterHelloFunction.Arn
              x-lpr:
                maxWaitMs: 25
                maxBatchSize: 4
                invokeMode: buffered
                timeoutMs: 8000
          /streaming/adapter/{greeting}:
            get:
              x-target-lambda: !GetAtt SampleStreamingAdapterHelloFunction.Arn
              x-lpr:
                maxWaitMs: 25
                maxBatchSize: 4
                invokeMode: response_stream
                timeoutMs: 8000
          /streaming/adapter/item/{id}:
            get:
              x-target-lambda: !GetAtt SampleStreamingAdapterHelloFunction.Arn
              x-lpr:
                maxWaitMs: 25
                maxBatchSize: 4
                invokeMode: response_stream
                timeoutMs: 8000
          /streaming/adapter/sse:
            get:
              x-target-lambda: !GetAtt SampleStreamingAdapterSseFunction.Arn
              x-lpr:
                maxWaitMs: 25
                maxBatchSize: 4
                invokeMode: response_stream
                timeoutMs: 8000
          /streaming/mode-a/python/{greeting}:
            get:
              x-target-lambda: !GetAtt SampleStreamingModeALayerProxyPythonHelloFunction.Arn
              x-lpr:
                maxWaitMs: 25
                maxBatchSize: 4
                invokeMode: response_stream
                timeoutMs: 8000
          /streaming/mode-a/python/item/{id}:
            get:
              x-target-lambda: !GetAtt SampleStreamingModeALayerProxyPythonHelloFunction.Arn
              x-lpr:
                maxWaitMs: 25
                maxBatchSize: 4
                invokeMode: response_stream
                timeoutMs: 8000
          /streaming/mode-a/node/{greeting}:
            get:
              x-target-lambda: !GetAtt SampleStreamingModeALayerProxyNodeHelloFunction.Arn
              x-lpr:
                maxWaitMs: 25
                maxBatchSize: 4
                invokeMode: response_stream
                timeoutMs: 8000
          /streaming/mode-a/node/item/{id}:
            get:
              x-target-lambda: !GetAtt SampleStreamingModeALayerProxyNodeHelloFunction.Arn
              x-lpr:
                maxWaitMs: 25
                maxBatchSize: 4
                invokeMode: response_stream
                timeoutMs: 8000

Outputs:
  BenchmarkItemsTableName:
    Value: !Ref BenchmarkItemsTable

  SampleBufferingSimpleHelloFunctionArn:
    Value: !GetAtt SampleBufferingSimpleHelloFunction.Arn

  SampleBufferingDynamicHelloFunctionArn:
    Value: !GetAtt SampleBufferingDynamicHelloFunction.Arn

  SampleStreamingSimpleHelloFunctionArn:
    Value: !GetAtt SampleStreamingSimpleHelloFunction.Arn

  SampleStreamingDynamicHelloFunctionArn:
    Value: !GetAtt SampleStreamingDynamicHelloFunction.Arn

  SampleBufferingAdapterHelloFunctionArn:
    Value: !GetAtt SampleBufferingAdapterHelloFunction.Arn

  SampleStreamingAdapterHelloFunctionArn:
    Value: !GetAtt SampleStreamingAdapterHelloFunction.Arn

  SampleStreamingAdapterSseFunctionArn:
    Value: !GetAtt SampleStreamingAdapterSseFunction.Arn

  SampleStreamingModeALayerProxyPythonHelloFunctionArn:
    Value: !GetAtt SampleStreamingModeALayerProxyPythonHelloFunction.Arn

  SampleStreamingModeALayerProxyNodeHelloFunctionArn:
    Value: !GetAtt SampleStreamingModeALayerProxyNodeHelloFunction.Arn

  DirectHelloFunctionArn:
    Value: !GetAtt DirectHelloFunction.Arn

  RouterServiceUrl:
    Value: !GetAtt RouterService.ServiceUrl

  RouterServiceBaseUrl:
    Value: !Sub "https://${RouterService.ServiceUrl}"

  DirectHelloUrl:
    Value: !GetAtt DirectHelloFunctionUrl.FunctionUrl

  DirectItemUrl:
    Value: !Sub "${DirectHelloFunctionUrl.FunctionUrl}item/hello"

  BufferingSimpleHelloUrl:
    Value: !Sub "https://${RouterService.ServiceUrl}/buffering/simple/hello"

  BufferingSimpleItemUrl:
    Value: !Sub "https://${RouterService.ServiceUrl}/buffering/simple/item/hello"

  BufferingDynamicHelloUrl:
    Value: !Sub "https://${RouterService.ServiceUrl}/buffering/dynamic/hello"

  BufferingDynamicItemUrl:
    Value: !Sub "https://${RouterService.ServiceUrl}/buffering/dynamic/item/hello"

  StreamingSimpleHelloUrl:
    Value: !Sub "https://${RouterService.ServiceUrl}/streaming/simple/hello"

  StreamingSimpleItemUrl:
    Value: !Sub "https://${RouterService.ServiceUrl}/streaming/simple/item/hello"

  StreamingDynamicHelloUrl:
    Value: !Sub "https://${RouterService.ServiceUrl}/streaming/dynamic/hello"

  StreamingDynamicItemUrl:
    Value: !Sub "https://${RouterService.ServiceUrl}/streaming/dynamic/item/hello"

  BufferingAdapterHelloUrl:
    Value: !Sub "https://${RouterService.ServiceUrl}/buffering/adapter/hello"

  BufferingAdapterItemUrl:
    Value: !Sub "https://${RouterService.ServiceUrl}/buffering/adapter/item/hello"

  StreamingAdapterHelloUrl:
    Value: !Sub "https://${RouterService.ServiceUrl}/streaming/adapter/hello"

  StreamingAdapterItemUrl:
    Value: !Sub "https://${RouterService.ServiceUrl}/streaming/adapter/item/hello"

  StreamingAdapterSseUrl:
    Value: !Sub "https://${RouterService.ServiceUrl}/streaming/adapter/sse"

  StreamingModeALayerProxyPythonHelloUrl:
    Value: !Sub "https://${RouterService.ServiceUrl}/streaming/mode-a/python/hello"

  StreamingModeALayerProxyPythonItemUrl:
    Value: !Sub "https://${RouterService.ServiceUrl}/streaming/mode-a/python/item/hello"

  StreamingModeALayerProxyNodeHelloUrl:
    Value: !Sub "https://${RouterService.ServiceUrl}/streaming/mode-a/node/hello"

  StreamingModeALayerProxyNodeItemUrl:
    Value: !Sub "https://${RouterService.ServiceUrl}/streaming/mode-a/node/item/hello"
