AWSTemplateFormatVersion: "2010-09-09"
Transform:
  - AWS::Serverless-2016-10-31
  - LprRouter
Description: lambda-parallel-router demo (App Runner + sample Lambda batch handlers)

Parameters:
  RouterImageIdentifier:
    Type: String
    Default: ""
    Description: Optional ECR image identifier override for the router container (defaults to the bootstrap export LprDefaultRouterImageIdentifier).
  OtelTracesEndpoint:
    Type: String
    Default: https://api.honeycomb.io/v1/traces
    Description: OTLP traces endpoint URL (used as-is, not modified by the router).
  OtelTracesProtocol:
    Type: String
    Default: http/protobuf
    AllowedValues:
      - http/protobuf
      - grpc
    Description: OTLP protocol to use for exporting traces.
  OtelHeadersSecretArn:
    Type: String
    Description: Secrets Manager secret ARN containing a JSON object of HTTP headers to send with OTLP requests.

Conditions:
  HasRouterImageIdentifier: !Not [!Equals [!Ref RouterImageIdentifier, ""]]

Globals:
  Function:
    Runtime: nodejs24.x
    Handler: app.handler
    Timeout: 10
    MemorySize: 256
    Tracing: Active
    LoggingConfig:
      ApplicationLogLevel: INFO
      LogFormat: JSON

Resources:

  # ------------------------------
  # Sample Lambda functions
  # ------------------------------
  SampleBufferingSimpleHelloFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/buffering-simple/
      FunctionName: !Sub '${AWS::StackName}-buffering-simple-hello'
      Description: Demo batch handler (buffered, simple).
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        EntryPoints:
          - app.ts
        Format: cjs
        Minify: false
        Sourcemap: false
        Target: es2020

  SampleBufferingDynamicHelloFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/buffering-dynamic/
      FunctionName: !Sub '${AWS::StackName}-buffering-dynamic-hello'
      Description: Demo batch handler (buffered, dynamic).
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        EntryPoints:
          - app.ts
        Format: cjs
        Minify: false
        Sourcemap: false
        Target: es2020

  SampleStreamingSimpleHelloFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/streaming-simple/
      FunctionName: !Sub '${AWS::StackName}-streaming-simple-hello'
      Description: Demo batch handler (streaming, simple).
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        EntryPoints:
          - app.ts
        Format: cjs
        Minify: false
        Sourcemap: false
        Target: es2020

  SampleStreamingDynamicHelloFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/streaming-dynamic/
      FunctionName: !Sub '${AWS::StackName}-streaming-dynamic-hello'
      Description: Demo batch handler (streaming, dynamic).
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        EntryPoints:
          - app.ts
        Format: cjs
        Minify: false
        Sourcemap: false
        Target: es2020

  SampleBufferingAdapterHelloFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/buffering-adapter/
      FunctionName: !Sub '${AWS::StackName}-buffering-adapter-hello'
      Description: Demo batch handler (buffered, adapter).
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        EntryPoints:
          - app.ts
        Format: cjs
        Minify: false
        Sourcemap: false
        Target: es2020

  SampleStreamingAdapterHelloFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/streaming-adapter/
      FunctionName: !Sub '${AWS::StackName}-streaming-adapter-hello'
      Description: Demo batch handler (streaming, adapter).
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        EntryPoints:
          - app.ts
        Format: cjs
        Minify: false
        Sourcemap: false
        Target: es2020

  SampleStreamingAdapterSseFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/streaming-adapter-sse/
      FunctionName: !Sub '${AWS::StackName}-streaming-adapter-sse'
      Description: Demo batch handler (streaming, adapter, SSE).
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        EntryPoints:
          - app.ts
        Format: cjs
        Minify: false
        Sourcemap: false
        Target: es2020

  DirectHelloFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/direct-hello/
      FunctionName: !Sub '${AWS::StackName}-direct-hello'
      Description: Demo handler exposed via a Lambda Function URL (direct invoke).
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        EntryPoints:
          - app.ts
        Format: cjs
        Minify: false
        Sourcemap: false
        Target: es2020

  DirectHelloFunctionUrl:
    Type: AWS::Lambda::Url
    Properties:
      AuthType: NONE
      TargetFunctionArn: !GetAtt DirectHelloFunction.Arn

  DirectHelloFunctionUrlPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunctionUrl
      FunctionName: !Ref DirectHelloFunction
      Principal: "*"
      FunctionUrlAuthType: NONE

  # ------------------------------
  # Router service (expanded by the LprRouter macro)
  # ------------------------------
  RouterService:
    Type: Lpr::Router::Service
    Properties:
      ServiceName: !Sub '${AWS::StackName}-service'
      ImageIdentifier: !If
        - HasRouterImageIdentifier
        - !Ref RouterImageIdentifier
        - !ImportValue LprDefaultRouterImageIdentifier
      Port: 8080
      Environment:
        RUST_LOG: info
      InstanceConfiguration:
        Cpu: "1 vCPU"
        Memory: "2 GB"
      AutoScalingConfiguration:
        MaxConcurrency: 100
        MinSize: 4
        MaxSize: 8
      RouterConfig:
        DefaultTimeoutMs: 2000
      ObservabilityConfiguration:
        Vendor: OTEL
        OpentelemetryConfiguration:
          TracesEndpoint: !Ref OtelTracesEndpoint
          Protocol: !Ref OtelTracesProtocol
          HeadersSecretArn: !Ref OtelHeadersSecretArn
      Spec:
        openapi: 3.0.0
        info:
          title: lambda-parallel-router demo
          version: "1"
        paths:
          /buffering/simple/{greeting}:
            get:
              x-target-lambda: !GetAtt SampleBufferingSimpleHelloFunction.Arn
              x-lpr:
                maxWaitMs: 25
                maxBatchSize: 4
                invokeMode: buffered
                timeoutMs: 8000
          /buffering/dynamic/{greeting}:
            get:
              x-target-lambda: !GetAtt SampleBufferingDynamicHelloFunction.Arn
              x-lpr:
                maxWaitMs: 100
                maxBatchSize: 16
                invokeMode: buffered
                timeoutMs: 8000
                dynamicWait:
                  minWaitMs: 1
                  targetRps: 50
                  steepness: 0.05
                  samplingIntervalMs: 100
                  smoothingSamples: 5
          /streaming/simple/{greeting}:
            get:
              x-target-lambda: !GetAtt SampleStreamingSimpleHelloFunction.Arn
              x-lpr:
                maxWaitMs: 25
                maxBatchSize: 4
                invokeMode: response_stream
                timeoutMs: 8000
          /streaming/dynamic/{greeting}:
            get:
              x-target-lambda: !GetAtt SampleStreamingDynamicHelloFunction.Arn
              x-lpr:
                maxWaitMs: 100
                maxBatchSize: 16
                invokeMode: response_stream
                timeoutMs: 8000
                dynamicWait:
                  minWaitMs: 1
                  targetRps: 50
                  steepness: 0.05
                  samplingIntervalMs: 100
                  smoothingSamples: 5
          /buffering/adapter/{greeting}:
            get:
              x-target-lambda: !GetAtt SampleBufferingAdapterHelloFunction.Arn
              x-lpr:
                maxWaitMs: 25
                maxBatchSize: 4
                invokeMode: buffered
                timeoutMs: 8000
          /streaming/adapter/{greeting}:
            get:
              x-target-lambda: !GetAtt SampleStreamingAdapterHelloFunction.Arn
              x-lpr:
                maxWaitMs: 25
                maxBatchSize: 4
                invokeMode: response_stream
                timeoutMs: 8000
          /streaming/adapter/sse:
            get:
              x-target-lambda: !GetAtt SampleStreamingAdapterSseFunction.Arn
              x-lpr:
                maxWaitMs: 25
                maxBatchSize: 4
                invokeMode: response_stream
                timeoutMs: 8000

Outputs:
  SampleBufferingSimpleHelloFunctionArn:
    Value: !GetAtt SampleBufferingSimpleHelloFunction.Arn

  SampleBufferingDynamicHelloFunctionArn:
    Value: !GetAtt SampleBufferingDynamicHelloFunction.Arn

  SampleStreamingSimpleHelloFunctionArn:
    Value: !GetAtt SampleStreamingSimpleHelloFunction.Arn

  SampleStreamingDynamicHelloFunctionArn:
    Value: !GetAtt SampleStreamingDynamicHelloFunction.Arn

  SampleBufferingAdapterHelloFunctionArn:
    Value: !GetAtt SampleBufferingAdapterHelloFunction.Arn

  SampleStreamingAdapterHelloFunctionArn:
    Value: !GetAtt SampleStreamingAdapterHelloFunction.Arn

  SampleStreamingAdapterSseFunctionArn:
    Value: !GetAtt SampleStreamingAdapterSseFunction.Arn

  DirectHelloFunctionArn:
    Value: !GetAtt DirectHelloFunction.Arn

  RouterImageIdentifier:
    Value: !Ref RouterImageIdentifier

  RouterServiceUrl:
    Value: !GetAtt RouterService.ServiceUrl

  RouterServiceBaseUrl:
    Value: !Sub "https://${RouterService.ServiceUrl}"

  DirectHelloUrl:
    Value: !GetAtt DirectHelloFunctionUrl.FunctionUrl

  BufferingSimpleHelloUrl:
    Value: !Sub "https://${RouterService.ServiceUrl}/buffering/simple/hello"

  BufferingDynamicHelloUrl:
    Value: !Sub "https://${RouterService.ServiceUrl}/buffering/dynamic/hello"

  StreamingSimpleHelloUrl:
    Value: !Sub "https://${RouterService.ServiceUrl}/streaming/simple/hello"

  StreamingDynamicHelloUrl:
    Value: !Sub "https://${RouterService.ServiceUrl}/streaming/dynamic/hello"

  BufferingAdapterHelloUrl:
    Value: !Sub "https://${RouterService.ServiceUrl}/buffering/adapter/hello"

  StreamingAdapterHelloUrl:
    Value: !Sub "https://${RouterService.ServiceUrl}/streaming/adapter/hello"

  StreamingAdapterSseUrl:
    Value: !Sub "https://${RouterService.ServiceUrl}/streaming/adapter/sse"
