AWSTemplateFormatVersion: "2010-09-09"
Transform:
  - AWS::Serverless-2016-10-31
  - LprRouter
Description: lambda-parallel-router demo (App Runner + sample Lambda batch handlers)

Parameters:
  RouterImageIdentifier:
    Type: String
    Description: ECR image identifier for the router container (e.g. 123456789012.dkr.ecr.us-east-1.amazonaws.com/lambda-parallel-router/router:latest).

Resources:
  # ------------------------------
  # Sample Lambda functions
  # ------------------------------
  SampleBufferedFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs20.x
      Handler: index.handler
      CodeUri: lambda/buffered/
      Description: Demo batch handler for buffered responses.
      MemorySize: 256
      Timeout: 10
      Policies:
        - AWSLambdaBasicExecutionRole

  SampleStreamingFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs20.x
      Handler: index.handler
      CodeUri: lambda/streaming/
      Description: Demo batch handler for NDJSON streaming responses.
      MemorySize: 256
      Timeout: 10
      Policies:
        - AWSLambdaBasicExecutionRole

  # ------------------------------
  # Router service (expanded by the LprRouter macro)
  # ------------------------------
  RouterService:
    Type: Lpr::Router::Service
    Properties:
      ImageIdentifier: !Ref RouterImageIdentifier
      Port: 8080
      Environment:
        RUST_LOG: info
      InvokeLambdaArns:
        - !GetAtt SampleBufferedFunction.Arn
        - !GetAtt SampleStreamingFunction.Arn
      RouterConfig: {}
      Spec:
        openapi: 3.0.0
        info:
          title: lambda-parallel-router demo
          version: "1"
        paths:
          /hello:
            get:
              x-target-lambda: !GetAtt SampleBufferedFunction.Arn
              x-lpr:
                max_wait_ms: 25
                max_batch_size: 4
                invoke_mode: buffered
          /hello-stream:
            get:
              x-target-lambda: !GetAtt SampleStreamingFunction.Arn
              x-lpr:
                max_wait_ms: 25
                max_batch_size: 4
                invoke_mode: response_stream

Outputs:
  SampleBufferedFunctionArn:
    Value: !GetAtt SampleBufferedFunction.Arn

  SampleStreamingFunctionArn:
    Value: !GetAtt SampleStreamingFunction.Arn

  RouterImageIdentifier:
    Value: !Ref RouterImageIdentifier

  RouterServiceUrl:
    Value: !GetAtt RouterService.ServiceUrl
